#24 hours ~ set to 'disabled' to disable automatic backups
delay: 01:00:00:00
#3 days ~ set to 'disabled' to disable old backup deletion
deleteifolderthan: 03:00:00:00
#you may use subfolders like 'plugins/Essentials'
backuplist:
 - world
 - plugins
 - ops.json